# GitHub Action: Deploy to GitHub Pages
# This workflow automatically deploys the static content from this private repository
# to the public lmyBTC.github.io repository.

name: Deploy to GitHub Pages

on:
  # Triggers the workflow on push events to the main branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to lmyBTC.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          # The SSH deploy key we added to the repository secrets
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # The target repository (your public GitHub Pages repo)
          external_repository: lmyBTC/lmyBTC.github.io
          # The branch to publish to in the target repository
          publish_branch: main
          # The directory to publish from this repository (root)
          publish_dir: ./
          # Exclude the workflow file itself from being published
          exclude_assets: '.github/'
          # A commit message for the deployment
          commit_message: "🚀 Deploy: ${{ github.event.head_commit.message }}"